### ISSUE TITLE
Use lambdas instead of Closure0-9

### ISSUE THREAD

**Issue by fenollp** [Himmele/Mindroid.cpp#1]
Hey
Curious: why don't you use C++11's lambda functions instead of [your Closure objects](https://github.com/Himmele/Mindroid.cpp/blob/master/mindroid/os/Closure.h)?

**Comment by Himmele** [comment]
When I developed Mindroid.cpp back in 2011 and 2012, I haven't taken a look into that. Currently I am planning to extend Mindroid.cpp with some kind of Reactive Extensions. Then I will also add C++ 11 lambdas.
