### ISSUE TITLE
Make error: undefined reference to 'testing::internal::*'

### ISSUE THREAD

**Issue by wangcan26** [Himmele/Mindroid.cpp#3]
I run make derectly under the Mindroid forder, however, it reports errors:
 
/root/WorkSpace/Mindroid.cpp/./gtest/gtest.h:1382: undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
bin/tests/SharedPreferences.o: In function `_ZN7testing8internal18CmpHelperEQFailureIN8mindroid2spINS2_3SetINS3_INS2_6StringEEEEEEEDnEENS_15AssertionResultEPKcSC_RKT_RKT0_':
/root/WorkSpace/Mindroid.cpp/./gtest/gtest.h:1382: undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
bin/tests/Strings.o: In function `Mindroid_Strings_Test::TestBody()':
/root/WorkSpace/Mindroid.cpp/tests/Strings.cpp:80: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/root/WorkSpace/Mindroid.cpp/tests/Strings.cpp:102: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
gtest/libgtest.a: In function `testing::internal::AssertHelper::operator=(testing::Message const&) const':
gtest-all.cc:(.text+0x46a): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
gtest-all.cc:(.text+0x476): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
gtest-all.cc:(.text+0x497): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
gtest-all.cc:(.text+0x4a8): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: gtest/libgtest.a: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value

**Comment by Himmele** [comment]
gtest is now build on the platfrom and the prebuilt static library is not used anymore. This should fix the problem.

**Comment by Himmele** [comment]
gtest is now build on the platfrom and the prebuilt static library is not used anymore. This should fix the problem.
