### ISSUE TITLE
Question: about the smart pointer sp<T>

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [Himmele/Mindroid.cpp#6]
Thanks for you great ideas and project. It's easy to understand for an Android developer.  Reading the sources, I have some doubt about the automatic memory management by `Object` and `sp<T>`. 

1.  How to deal with circular references?  What's the different with `std::shared_ptr`? 
https://github.com/Himmele/Mindroid.cpp/blob/f3c3d5fd734d0f0c0629265ff2a8abc7d49635af/src/mindroid/os/ServiceManager.h#L58C1-L88C7
```
class ProcessRecord :
            public Object {
    public:
        ProcessRecord(const sp<String>& name, const sp<IProcess>& process);
        void addService(const sp<ComponentName>& component, const sp<ServiceRecord>& service);
        void removeService(const sp<ComponentName>& component);
        sp<ServiceRecord> getService(const sp<ComponentName>& component);
        bool containsService(const sp<ComponentName>& component);
        size_t numServices() const;

        sp<String> name;
        sp<IProcess> process;
        sp<HashMap<sp<ComponentName>, sp<ServiceRecord>>> services;
    };

class ServiceRecord :
            public Object {
    public:
        ServiceRecord(const sp<String>& name, const sp<ProcessRecord>& processRecord, bool systemService);
        void addServiceConnection(const sp<ServiceConnection>& conn);
        void removeServiceConnection(const sp<ServiceConnection> conn);
        size_t getNumServiceConnections() const;
        bool hasServiceConnection(const sp<ServiceConnection>& conn) const;

        sp<String> name;
        sp<ProcessRecord> processRecord;
        bool systemService;
        bool alive;
        bool running;
        sp<ArrayList<sp<ServiceConnection>>> serviceConnections;
    };
```
`ProcessRecord` and `ServiceRecord`,  they are both holding the strong references to each other.

2. Multiple Inheritance from the `Object`, how to auto deal with references of the object? 
https://github.com/Himmele/Mindroid.cpp/blob/f3c3d5fd734d0f0c0629265ff2a8abc7d49635af/src/mindroid/content/pm/IPackageManager.h#L44

**Comment by Himmele** [comment]
1. To deal with circular references you have to break the circle at one point using a weak pointer wp<T>.
The biggest difference compared to std::shared_ptr is that std::shared_ptr holds the reference counter within std::shared_ptr and sp<T> holds the reference counter within the Object, not sp<T>.

2. To do multiple inheritance correctly one needs to inherit virtual public from the Object base class to make sure there is always only one base Object. This is currently not done correctly in all places of Mindroid and should be fixed.
